<?php
/**
* @package Joomla
* @subpackage Fabrik
* @copyright Copyright (C) 2005 Rob Clayburn. All rights reserved.
* @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.php
*/

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die();

//require the abstract plugin classes
require_once(COM_FABRIK_FRONTEND.DS.'models'.DS.'plugin.php');
require_once(COM_FABRIK_FRONTEND.DS.'models'.DS.'validation_rule.php');

class FabrikModelisgreaterorlessthan extends FabrikModelValidationRule {

	var $_pluginName = 'isgreaterorlessthan';

	/** @param string classname used for formatting error messages generated by plugin */
	var $_className = 'notempty isgreaterorlessthan';

	/**
	 * validate the elements data against the rule
	 * @param string data to check
	 * @param object element
	 * @param int plugin sequence ref
	 * @param int repeat group count
	 * @return bol true if validation passes, false if fails
	 */

	function validate($data, &$element, $c, $repeat_count = 0)
	{
		//could be a dropdown with multivalues
		if (is_array($data)) {
			$data = implode('', $data);
		}
 		$params =& $this->getParams();
 		$formdata = $element->getForm()->_formData;
 		$cond = $params->get('isgreaterorlessthan-greaterthan');
 		$cond = $cond[$c] == '1' ? '>' : '<';
 		$compare = $params->get('isgreaterorlessthan-comparewith');
 		// $$$ rob  not sure why but when last testing compare was not an array
 		$compare = is_array($compare) ? $compare[$c] : $compare;
 		$compareEl = $element->getForm()->getElement($compare);

 		// $$$ rob get the acutal element's value from the model rather than using $formdata as for dates with times this wont include the time
 		//$compare = JArrayHelper::getValue($formdata, $compare.'_raw', JArrayHelper::getValue($formdata, $compare, ''));
 		$compareVal = $compareEl->getValue($formdata, $repeat_count, array('runplugins'=>0, 'use_default'=>false));
 		$res = $element->greaterOrLessThan($data, $cond, $compareVal);
 		return $res;
	}

}
?>